void ls(char command_str[][50], int pos);
int ls_l(char pathname[], char *filename);
void cd(char command_str[][50], int pos, char home_dir[]);
void pinfo(char command[][50], int pos, char home_dir[]);
void echo(char command_str[][50], int pos);
void event_listener(int signum);
int clocker(char command_str[][50]);
void command_extract(char command_str[], char home_dir[]);
void remove_proc(int kill_id[], int kill_count);
void change_display_path(char home_dir[]);
void setenvar(char command_str[][50]);
void unsetenvar(char command_str[][50]);
int pwd();
void jobs();
void kjobs(char command_str[][50]);
void overkill();
void fg(char command_str[][50]);
void bg(char command_str[][50]);
void CTRL_Z(int sig);
